name: Test de mon action

on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dire bonjour avec mon action
        uses: bennayya/action_perso@main
        with:
          nom: "bennayya"
          langue: "fr"